include: package:lints/recommended.yaml

analyzer:
  exclude: [lib/raw/proto/**, example/**]

linter:
  rules:
    omit_local_variable_types: false
    unnecessary_this: false
    non_constant_identifier_names: false
    constant_identifier_names: false
    overridden_fields: false
